import { slate, slateDark, green, greenDark, red } from "@radix-ui/colors";

export const colors = {
  backgroundColorLight: slate.slate1,
  backgroundColorDark: slateDark.slate1,
  tintColorLight: green.green12,
  tintColorDark: greenDark.green12,
  accentColor: green.green9,
  slate1: slate.slate1,
  slate2: slate.slate2,
  slate3: slate.slate3,
  slate4: slate.slate4,
  slate5: slate.slate5,
  slate6: slate.slate6,
  slate7: slate.slate7,
  slate8: slate.slate8,
  slate9: slate.slate9,
  slate10: slate.slate10,
  slate11: slate.slate11,
  slate12: slate.slate12,

  darkSlate1: slateDark.slate1,
  darkSlate2: slateDark.slate2,
  darkSlate3: slateDark.slate3,
  darkSlate4: slateDark.slate4,
  darkSlate5: slateDark.slate5,
  darkSlate6: slateDark.slate6,
  darkSlate7: slateDark.slate7,
  darkSlate8: slateDark.slate8,
  darkSlate9: slateDark.slate9,
  darkSlate10: slateDark.slate10,
  darkSlate11: slateDark.slate11,
  darkSlate12: slateDark.slate12,

  green1: green.green1,
  green2: green.green2,
  green3: green.green3,
  green4: green.green4,
  green5: green.green5,
  green6: green.green6,
  green7: green.green7,
  green8: green.green8,
  green9: green.green9,
  green10: green.green10,
  green11: green.green11,
  green12: green.green12,

  darkGreen1: greenDark.green1,
  darkGreen2: greenDark.green2,
  darkGreen3: greenDark.green3,
  darkGreen4: greenDark.green4,
  darkGreen5: greenDark.green5,
  darkGreen6: greenDark.green6,
  darkGreen7: greenDark.green7,
  darkGreen8: greenDark.green8,
  darkGreen9: greenDark.green9,
  darkGreen10: greenDark.green10,
  darkGreen11: greenDark.green11,
  darkGreen12: greenDark.green12,

  red1: red.red1,
  red2: red.red2,
  red3: red.red3,
  red4: red.red4,
  red5: red.red5,
  red6: red.red6,
  red7: red.red7,
  red8: red.red8,
  red9: red.red9,
  red10: red.red10,
  red11: red.red11,
  red12: red.red12,

  darkRed1: red.red1,
  darkRed2: red.red2,
  darkRed3: red.red3,
  darkRed4: red.red4,
  darkRed5: red.red5,
  darkRed6: red.red6,
  darkRed7: red.red7,
  darkRed8: red.red8,
  darkRed9: red.red9,
  darkRed10: red.red10,
  darkRed11: red.red11,
  darkRed12: red.red12,
};
